---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opencensus
  labels:
    app: {{ .Release.Name }}-opencensus
    sys: {{ include "helloweb.name" . }}
data:
  oc-agent-config: |
    receivers:
      opencensus:
      address: "0.0.0.0:55678"
    queued-exporters:
      jaeger-all-in-one:
        num-workers: 1
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: http://192.168.1.68:14268/api/traces

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-opencensus
  labels:
    app: {{ .Release.Name }}-opencensus
    sys: {{ include "helloweb.name" . }}
spec:
  containers:
  - name: opencensus
    image: {{ .Values.OCImage}}
    args: [ "--config=/conf/agent.yaml", "--log-level=debug", "--logging-exporter" ]
    ports:
    - containerPort: 55678
    - containerPort: 55679
    volumeMounts:
    - name: config-vol
      mountPath: /conf
  volumes:
  - name: config-vol
    configMap:
      name: {{ .Release.Name }}-opencensus
      items:
      - key: oc-agent-config
        path: agent.yaml

