apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: siuyin/junk
    context: .
    docker: 
      dockerfile: secureweb.dockerfile
deploy:
  kustomize:
    path: secureweb.kustomize/overlays/dev
profiles:
- name: prod
  deploy:
    kustomize:
      path: secureweb.kustomize/overlays/prod
