apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: siuyin/junk
    context: .
    docker: 
      dockerfile: ticktock.dockerfile
deploy:
  kustomize:
    path: ticktock.kustomize/base
profiles:
- name: prod
  deploy:
    kustomize:
      path: ticktock.kustomize/overlays/prod
- name: test
  deploy:
    kustomize:
      path: ticktock.kustomize/overlays/test
