# kustomization for keycloak authentication server
namePrefix: kcl-
commonLabels:
  sys: keycloak
secretGenerator:
- name: postgres
  envs:
  - postgres.secret
configMapGenerator:
- name: postgres
  literals:
  - POSTGRES_DB=keycloak
resources:
#- keycloak-deployment.yaml
- postgres-deployment.yaml
