# kustomization for keycloak authentication server
namePrefix: kcl-
commonLabels:
  sys: keycloak
secretGenerator:
- name: postgres
  envs:
  - postgres.secret
- name: keycloak
  envs:
  - keycloak.secret
configMapGenerator:
- name: keycloak
  literals:
  - DB_ADDR=kcl-postgres-dev:5432 # kustomize me
resources:
- keycloak-deployment.yaml
- postgres-deployment.yaml
