# Run with "skaffold build" to create a tagged siuyin/junk:{git_commit} image.
apiVersion: skaffold/v4beta5
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      prefix: em-
  artifacts:
    # Skaffold will use this as your image name and push it here after building
    - image: siuyin/junk
      # We are using Docker as our builder here
      docker:
        # Pass the args we want to Docker during build