apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticktock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticktock
  template:
    metadata:
      labels:
        app: ticktock
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: ticktock
        image: siuyin/junk
        envFrom:
        - configMapRef:
            name: ticktock
