apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticktock
  labels:
    sys: ticktock
spec:
  replicas: 1
  selector:
    matchLabels:
      sys: ticktock
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: ticktock
        image: siuyin/junk
        env:
        - name: STAGE
          value: dev
        - name: MSG
          value: D-message

