namePrefix: tck-
commonLabels:
  sys: ticktock
configMapGenerator:
- name: ticktock
  literals:
  - STAGE=dev
  - MSG=CM-Message
resources:
- deployment.yaml
- deployment-nats-streaming.yaml
- nats-streaming-svc.yaml
