apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
  labels:
    sys: ticktock
spec:
  type: NodePort
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
      name: nats
  selector:
    sys: ticktock
