// Code generated by "stringer -type=drug"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[acetaminophen-0]
	_ = x[salicylicAsid-1]
	_ = x[vitB-2]
}

const _drug_name = "acetaminophensalicylicAsidvitB"

var _drug_index = [...]uint8{0, 13, 26, 30}

func (i drug) String() string {
	if i < 0 || i >= drug(len(_drug_index)-1) {
		return "drug(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _drug_name[_drug_index[i]:_drug_index[i+1]]
}
