// Code generated by "stringer -type=pill"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[paracetamol-0]
	_ = x[asprin-1]
	_ = x[cyanocobalamin-2]
}

const _pill_name = "paracetamolasprincyanocobalamin"

var _pill_index = [...]uint8{0, 11, 17, 31}

func (i pill) String() string {
	if i < 0 || i >= pill(len(_pill_index)-1) {
		return "pill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pill_name[_pill_index[i]:_pill_index[i+1]]
}
