apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: siuyin/junk
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.RELEASE}}"
